# Modules
- color: "fbca04"
  description: "This issue or pull request is related to resource-group module."
  name: ":floppy_disk: resource-group"
- color: "fbca04"
  description: "This issue or pull request is related to s3-archive-bucket module."
  name: ":floppy_disk: s3-archive-bucket"
- color: "fbca04"
  description: "This issue or pull request is related to sqs-aws-event-queue module."
  name: ":floppy_disk: sqs-aws-event-queue"
